name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/deploy.yml
      - index.html
      - package-lock.json
      - package.json
      - public/**
      - src/**
      - svelte.config.js
      - config/engineering/tsconfig/**
      - tsconfig*.json
      - vite.config.ts
  workflow_dispatch:

permissions: {}

jobs:
  pages:
    name: Build and deploy Pages
    permissions:
      contents: read
      packages: read
      pages: write
      id-token: write
    uses: jrmoulckers/.github/.github/workflows/reusable-deploy-pages.yml@4162bad33b949a7cf5f2d0b1b88b33fd71324128
    with:
      node-version: '22'
      package-manager: npm
      build-command: npm run build
      output-dir: dist
